class JourneyStage {
 constructor(section){
  this.section=section;this.listeners=[];this.motion=matchMedia('(prefers-reduced-motion: reduce)');this.fine=matchMedia('(hover: hover) and (pointer: fine)');this.frame=0;this.time=0;this.visible=false;this.paused=false;this.destroyed=false;section.journeyStage=this;
  const listen=(el,type,fn,options)=>{el.addEventListener(type,fn,options);this.listeners.push(()=>el.removeEventListener(type,fn,options));};
  this.copy=section.querySelector('.journey-copy');this.texts=[...this.copy.querySelectorAll('h1,h2,.prose p')];
  this.texts.forEach(el=>{el.classList.add('journey-dimensional');const face=document.createElement('span');face.className='journey-text-face';while(el.firstChild)face.append(el.firstChild);el.append(face);for(let i=0;i<(el.matches('p')?1:4);i++){const depth=document.createElement('span');depth.className='journey-text-depth';depth.textContent=face.textContent;depth.setAttribute('aria-hidden','true');depth.style.setProperty('--text-depth',i+'px');el.prepend(depth);}});
  this.canvas=document.createElement('canvas');this.canvas.className='journey-fireflies';this.canvas.setAttribute('aria-hidden','true');section.prepend(this.canvas);this.ctx=this.canvas.getContext('2d');
  this.beam=document.createElement('div');this.beam.className='journey-beam';this.beam.setAttribute('aria-hidden','true');this.beam.innerHTML='<svg viewBox="0 0 600 900" preserveAspectRatio="none"><defs><linearGradient id="journey-beam-fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#f0f4ff" stop-opacity=".22"/><stop offset=".45" stop-color="#e9efff" stop-opacity=".085"/><stop offset=".85" stop-color="#e9efff" stop-opacity=".035"/><stop offset="1" stop-color="#e9efff" stop-opacity="0"/></linearGradient><filter id="journey-beam-soft" x="-30%" y="-10%" width="160%" height="120%"><feGaussianBlur stdDeviation="7"/></filter></defs><path d="M287 0H313L550 870H50Z" fill="url(#journey-beam-fade)" filter="url(#journey-beam-soft)"/></svg>';section.querySelector('.medal-stage').prepend(this.beam);
  this.beam.querySelector('path').setAttribute('d','M300 18L550 870H50Z');
  this.beam.querySelectorAll('stop').forEach((stop,i)=>stop.setAttribute('stop-opacity',['.42','.21','.10','0'][i]));

  this.particles=Array.from({length:44},()=>({x:Math.random(),y:Math.random(),r:.6+Math.random()*1.05,phase:Math.random()*Math.PI*2,speed:2+Math.random()*4,drift:12+Math.random()*24}));
  const neutral=()=>{this.copy.style.setProperty('--stage-pitch','0deg');this.copy.style.setProperty('--stage-yaw','0deg');};
  listen(section,'pointermove',e=>{if(e.pointerType!=='mouse'||e.buttons||this.motion.matches||!this.fine.matches)return;const r=section.getBoundingClientRect(),x=Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),y=Math.max(-1,Math.min(1,e.clientY/innerHeight*2-1));this.copy.style.setProperty('--stage-pitch',(-y*1.8).toFixed(2)+'deg');this.copy.style.setProperty('--stage-yaw',(x*3.2).toFixed(2)+'deg');},{passive:true});listen(section,'pointerleave',neutral);listen(window,'blur',neutral);listen(this.motion,'change',()=>{neutral();this.draw();this.sync();});listen(this.fine,'change',neutral);listen(document,'visibilitychange',()=>this.sync());
  this.intersection=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting;this.sync();},{threshold:0});this.intersection.observe(section);this.bodyObserver=new MutationObserver(()=>this.sync());this.bodyObserver.observe(document.body,{attributes:true,attributeFilter:['class']});
  this.controls=section.querySelector('.medal-controls');this.controlsParent=this.controls.parentElement;section.append(this.controls);
  this.entrance=new SectionEntrance(section,'journey');
  this.resize=new ResizeObserver(()=>this.measure());this.resize.observe(section);this.measure();this.sync();
 }
 measure(){this.width=this.section.clientWidth;this.height=this.section.clientHeight;const ratio=Math.min(devicePixelRatio,1.5,1800/Math.max(1,this.height));this.canvas.width=Math.round(this.width*ratio);this.canvas.height=Math.round(this.height*ratio);this.ctx?.setTransform(ratio,0,0,ratio,0,0);this.draw();}
 draw(){if(!this.ctx||!this.width)return;const c=this.ctx,w=this.width,h=this.height;c.clearRect(0,0,w,h);const count=w<650?24:44;for(const p of this.particles.slice(0,count)){const x=p.x*w+Math.sin(this.time*.16+p.phase)*p.drift,y=((p.y*h-this.time*p.speed)%h+h)%h,edge=Math.min(1,y/70,(h-y)/70),alpha=(.055+.16*(.5+.5*Math.sin(this.time*.6+p.phase)))*edge;c.globalAlpha=alpha;const glow=c.createRadialGradient(x,y,0,x,y,p.r*5);glow.addColorStop(0,'#ffffff');glow.addColorStop(.16,'#f4f7ff');glow.addColorStop(1,'#ffffff00');c.fillStyle=glow;c.beginPath();c.arc(x,y,p.r*5,0,Math.PI*2);c.fill();c.globalAlpha=alpha*1.9;c.fillStyle='#fff';c.beginPath();c.arc(x,y,p.r*.5,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 sync(){if(this.destroyed)return;const running=this.visible&&!document.hidden&&!document.body.classList.contains('modal-open')&&!this.motion.matches&&!this.paused;this.copy.style.animationPlayState=running?'running':'paused';this.section.dataset.stageMotion=this.motion.matches?'reduced':running?'running':'paused';if(!running){cancelAnimationFrame(this.frame);this.frame=0;this.previous=0;return;}if(this.frame)return;this.previous=0;const tick=t=>{if(this.destroyed)return;if(!this.previous)this.previous=t;if(t-this.previous>=32){this.time+=Math.min(.08,(t-this.previous)/1000);this.previous=t;this.draw();}this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);}
 destroy(){this.destroyed=true;cancelAnimationFrame(this.frame);this.entrance.destroy();this.controlsParent.append(this.controls);this.resize.disconnect();this.intersection.disconnect();this.bodyObserver.disconnect();this.listeners.forEach(off=>off());this.canvas.remove();this.beam.remove();this.texts.forEach(el=>{el.querySelectorAll('.journey-text-depth').forEach(n=>n.remove());const face=el.querySelector('.journey-text-face');if(face)face.replaceWith(...face.childNodes);el.classList.remove('journey-dimensional');});this.copy.style.removeProperty('--stage-pitch');this.copy.style.removeProperty('--stage-yaw');delete this.section.journeyStage;}
}
